FROM node:18-alpine AS base

RUN corepack enable && corepack prepare pnpm@latest-10 --activate

WORKDIR /app

COPY package.json pnpm-lock.yaml ./
RUN pnpm install

COPY . .

# ENV CHOKIDAR_USEPOLLING=true

CMD ["pnpm", "start:dev"]
